title: "Starter Template"
author: "Jordan Barhorst"
email: jordan.barhorst@gmail.com
keywords: "comma, separated, keywords"
description: "Simple boilerplate for quickly setting up Jekyll with Normalize, Bourbon and Neat."

baseurl: "/starter-kit" # the subpath of your site, e.g. /blog/

markdown: kramdown

exclude: ['assets/src', 'node_modules', 'package.json', 'gulpfile.js', 'LICENSE', 'README.md', 'bourbonify-jekyll.sublime-project', 'bower_components', 'bower.json']

timezone: Europe/Warsaw

permalink: none
